"""Tests for the human-facing ``factory skill`` commands.

Three properties are what these commands are *for*, so they are asserted
directly rather than implied:

- ``skill path`` and ``skill validate`` are read-only. They create nothing --
  not the data directory, not a generated file, not an overlay.
- ``skill refresh`` is the only write path, and it writes exactly one thing:
  the generated file for the current dependency fingerprint. It creates no
  run and no worktree, and never touches the human-owned overlay.
- A refusal (a failed researcher, unverified guidance) leaves the previously
  stored generated bytes exactly as they were.

Only the agent runtime -- the external model boundary -- is ever replaced;
the repository profiler, the skill manager, merging and validation are the
real implementations throughout.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest
import yaml
from typer.testing import CliRunner

import software_agent_factory
from software_agent_factory import cli
from software_agent_factory.agents import AgentRequest, AgentResult, FakeAgentRuntime
from software_agent_factory.config import DEFAULT_CONFIG_FILENAME
from software_agent_factory.models import (
    AgentPurpose,
    AgentRole,
    RepositorySkill,
    SkillGuidance,
    SkillSource,
    SkillTarget,
)
from software_agent_factory.repository_profile import profile_repository

runner = CliRunner()

VALID_OVERLAY = """
mode: extend
polish:
  summary: House style for this repository.
  guidance:
    - Prefer the smallest change that satisfies the acceptance criteria.
""".lstrip()


@pytest.fixture(autouse=True)
def isolated_git_env(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("GIT_CONFIG_GLOBAL", os.devnull)
    monkeypatch.setenv("GIT_CONFIG_SYSTEM", os.devnull)
    monkeypatch.setenv("GIT_AUTHOR_NAME", "Factory Test")
    monkeypatch.setenv("GIT_AUTHOR_EMAIL", "factory-test@example.invalid")
    monkeypatch.setenv("GIT_COMMITTER_NAME", "Factory Test")
    monkeypatch.setenv("GIT_COMMITTER_EMAIL", "factory-test@example.invalid")
    monkeypatch.setenv("GIT_TERMINAL_PROMPT", "0")


def _git(cwd: Path, *args: str) -> str:
    result = subprocess.run(["git", "-C", str(cwd), *args], capture_output=True, text=True)
    assert result.returncode == 0, f"git {args} failed: {result.stderr}"
    return result.stdout


@pytest.fixture
def skill_repo(tmp_path: Path) -> Path:
    """A repository whose profile carries dependencies the deterministic fake
    researcher can ground in the configured official origins."""
    repo = tmp_path / "source"
    repo.mkdir()
    _git(repo, "init", "-b", "main")
    _git(repo, "config", "user.email", "factory-test@example.invalid")
    _git(repo, "config", "user.name", "Factory Test")
    _git(repo, "config", "commit.gpgsign", "false")
    (repo / "pyproject.toml").write_text(
        '[project]\nname = "demo"\nversion = "0.1.0"\n'
        'requires-python = ">=3.13"\ndependencies = ["pytest>=8.0"]\n',
        encoding="utf-8",
    )
    (repo / "README.md").write_text("hello\n", encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-m", "initial commit")
    return repo


@pytest.fixture
def missing_data_dir(tmp_path: Path) -> Path:
    """A data directory path that does not exist and must stay that way."""
    return tmp_path / "never-created"


@pytest.fixture
def path_without(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Replace ``PATH`` with a directory containing only the named shims."""

    def _configure(*available: str) -> Path:
        bin_dir = tmp_path / "fake-bin"
        bin_dir.mkdir(exist_ok=True)
        for name in available:
            shim = bin_dir / name
            shim.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
            shim.chmod(0o755)
        monkeypatch.setenv("PATH", str(bin_dir))
        return bin_dir

    return _configure


def _config_file(path: Path, data_dir: Path, *, polish_enabled: bool = True) -> Path:
    packaged = Path(software_agent_factory.__file__).parent / DEFAULT_CONFIG_FILENAME
    payload = yaml.safe_load(packaged.read_text(encoding="utf-8"))
    payload["factory"]["data_dir"] = str(data_dir)
    payload["polish"]["enabled"] = polish_enabled
    path.write_text(yaml.safe_dump(payload), encoding="utf-8")
    return path


def _install_runtime(monkeypatch: pytest.MonkeyPatch, runtime: FakeAgentRuntime) -> None:
    """Replace only the external model boundary the command would build."""
    monkeypatch.setattr(cli, "_build_runtime", lambda _choice: runtime)


def _refresh(repo: Path, data_dir: Path, *extra: str):
    return runner.invoke(
        cli.app, ["skill", "refresh", "--repo", str(repo), "--data-dir", str(data_dir), *extra]
    )


def _validate(repo: Path, data_dir: Path, *extra: str):
    return runner.invoke(
        cli.app, ["skill", "validate", "--repo", str(repo), "--data-dir", str(data_dir), *extra]
    )


def _skill_path(repo: Path, data_dir: Path, *extra: str):
    return runner.invoke(
        cli.app, ["skill", "path", "--repo", str(repo), "--data-dir", str(data_dir), *extra]
    )


def _line(output: str, prefix: str) -> str:
    for line in output.splitlines():
        if line.startswith(prefix):
            return line
    raise AssertionError(f"no {prefix!r} line in output:\n{output}")


def _generated_path(repo: Path, data_dir: Path) -> Path:
    fingerprint = profile_repository(repo).dependency_fingerprint
    key = _line(_skill_path(repo, data_dir).output, "repository key: ").split(": ", 1)[1]
    return data_dir / "repository-skills" / "v1" / key / "generated" / f"{fingerprint}.json"


def _overlay_path(repo: Path, data_dir: Path) -> Path:
    key = _line(_skill_path(repo, data_dir).output, "repository key: ").split(": ", 1)[1]
    return data_dir / "repository-skills" / "v1" / key / "repository-skill-overlay.yaml"


# -- factory skill path ----------------------------------------------------


def test_skill_path_reports_both_paths_without_creating_anything(
    skill_repo: Path, missing_data_dir: Path
) -> None:
    result = _skill_path(skill_repo, missing_data_dir)

    assert result.exit_code == 0, result.output
    fingerprint = profile_repository(skill_repo).dependency_fingerprint
    assert f"dependency fingerprint: {fingerprint}" in result.output
    assert _line(result.output, "repository key: ").split(": ", 1)[1]
    assert _line(result.output, "generated skill: ").endswith("(absent)")
    assert _line(result.output, "overlay: ").endswith("(absent)")
    assert f"{fingerprint}.json" in result.output
    assert "repository-skill-overlay.yaml" in result.output
    assert not missing_data_dir.exists()


def test_skill_path_reports_presence_of_a_stored_skill(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0

    result = _skill_path(skill_repo, data_dir)

    assert result.exit_code == 0, result.output
    assert _line(result.output, "generated skill: ").endswith("(present)")
    assert _line(result.output, "overlay: ").endswith("(absent)")


def test_skill_path_is_identical_from_a_linked_worktree(
    skill_repo: Path, missing_data_dir: Path, tmp_path: Path
) -> None:
    """Identity is the Git *common* directory, so a worktree and its main
    checkout share one skill directory rather than generating twice."""
    worktree = tmp_path / "linked-worktree"
    _git(skill_repo, "worktree", "add", str(worktree), "-b", "topic")

    from_main = _skill_path(skill_repo, missing_data_dir)
    from_worktree = _skill_path(worktree, missing_data_dir)

    assert from_main.exit_code == 0, from_main.output
    assert from_worktree.exit_code == 0, from_worktree.output
    for prefix in ("repository key: ", "generated skill: ", "overlay: "):
        assert _line(from_main.output, prefix) == _line(from_worktree.output, prefix)
    assert not missing_data_dir.exists()


def test_skill_path_requires_git(skill_repo: Path, missing_data_dir: Path, path_without) -> None:
    path_without()

    result = _skill_path(skill_repo, missing_data_dir)

    assert result.exit_code == 2
    assert "missing required executable(s) on PATH: git" in result.output
    assert "Traceback" not in result.output
    assert not missing_data_dir.exists()


def test_skill_path_refuses_a_directory_outside_a_repository(
    tmp_path: Path, missing_data_dir: Path
) -> None:
    plain = tmp_path / "plain"
    plain.mkdir()

    result = _skill_path(plain, missing_data_dir)

    assert result.exit_code == 2
    assert "cannot resolve repository skill storage" in result.output
    assert "Traceback" not in result.output
    assert not missing_data_dir.exists()


# -- factory skill validate ------------------------------------------------


def test_validate_reports_a_missing_generated_skill_and_creates_nothing(
    skill_repo: Path, missing_data_dir: Path
) -> None:
    result = _validate(skill_repo, missing_data_dir)

    assert result.exit_code == 1, result.output
    assert _line(result.output, "generated skill: ").startswith("generated skill: missing")
    assert "factory skill refresh" in result.output
    assert _line(result.output, "overlay: ").startswith("overlay: missing")
    assert "a missing overlay is normal" in result.output
    assert not missing_data_dir.exists()


def test_validate_accepts_a_stored_skill_with_no_overlay(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0

    result = _validate(skill_repo, data_dir)

    assert result.exit_code == 0, result.output
    assert _line(result.output, "generated skill: ").startswith("generated skill: valid")
    assert _line(result.output, "overlay: ").startswith("overlay: missing")
    assert not _overlay_path(skill_repo, data_dir).exists()


def test_validate_reports_a_valid_overlay_and_the_effective_skill(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0
    overlay_path = _overlay_path(skill_repo, data_dir)
    overlay_path.write_text(VALID_OVERLAY, encoding="utf-8")

    result = _validate(skill_repo, data_dir)

    assert result.exit_code == 0, result.output
    assert _line(result.output, "overlay: ").startswith("overlay: valid")
    assert "effective skill: valid" in result.output
    assert overlay_path.read_text(encoding="utf-8") == VALID_OVERLAY


def test_validate_reports_a_malformed_overlay_without_rewriting_it(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0
    overlay_path = _overlay_path(skill_repo, data_dir)
    # Claims machine-owned provenance the overlay schema forbids, and its
    # guidance section is the wrong shape.
    malformed = "mode: extend\ndependency_fingerprint: " + "a" * 64 + "\npolish: not-a-mapping\n"
    overlay_path.write_text(malformed, encoding="utf-8")
    original = overlay_path.read_bytes()

    result = _validate(skill_repo, data_dir)

    assert result.exit_code == 1, result.output
    assert _line(result.output, "generated skill: ").startswith("generated skill: valid")
    assert _line(result.output, "overlay: ").startswith("overlay: invalid")
    assert "dependency_fingerprint" in result.output
    assert "edit it by hand or remove it" in result.output
    assert "effective skill" not in result.output
    assert overlay_path.read_bytes() == original


def test_validate_reports_unparsable_overlay_yaml(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0
    overlay_path = _overlay_path(skill_repo, data_dir)
    overlay_path.write_text("mode: extend\n  polish: [unclosed\n", encoding="utf-8")
    original = overlay_path.read_bytes()

    result = _validate(skill_repo, data_dir)

    assert result.exit_code == 1, result.output
    assert _line(result.output, "overlay: ").startswith("overlay: invalid")
    assert "YAML" in result.output
    assert overlay_path.read_bytes() == original


def test_validate_reports_an_unmergeable_overlay_as_an_invalid_effective_skill(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The overlay parses, but extending would exceed what a repository skill
    allows: valid overlay, invalid effective skill."""
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0
    overlay_path = _overlay_path(skill_repo, data_dir)
    entries = "\n".join(f"    - Overlay guidance entry {index}." for index in range(12))
    overlay_path.write_text(
        f"mode: extend\npolish:\n  summary: Extra guidance.\n  guidance:\n{entries}\n",
        encoding="utf-8",
    )
    original = overlay_path.read_bytes()

    result = _validate(skill_repo, data_dir)

    assert result.exit_code == 1, result.output
    assert _line(result.output, "overlay: ").startswith("overlay: valid")
    assert "effective skill: invalid" in result.output
    assert overlay_path.read_bytes() == original


def test_validate_reports_a_corrupt_generated_file_as_invalid(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0
    generated_path = _generated_path(skill_repo, data_dir)
    generated_path.write_text('{"generator_version": 1}\n', encoding="utf-8")

    result = _validate(skill_repo, data_dir)

    assert result.exit_code == 1, result.output
    assert _line(result.output, "generated skill: ").startswith("generated skill: invalid")
    assert "Traceback" not in result.output


# -- factory skill refresh -------------------------------------------------


def test_refresh_creates_the_generated_skill_without_a_run_or_a_worktree(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())

    result = _refresh(skill_repo, data_dir)

    assert result.exit_code == 0, result.output
    generated_path = _generated_path(skill_repo, data_dir)
    assert _line(result.output, "created generated skill: ").endswith(str(generated_path))
    stored = RepositorySkill.model_validate_json(generated_path.read_bytes())
    assert stored.dependency_fingerprint == profile_repository(skill_repo).dependency_fingerprint

    assert not (data_dir / "runs").exists()
    assert not (data_dir / "workspaces").exists()
    assert _git(skill_repo, "worktree", "list").strip().count("\n") == 0
    assert _git(skill_repo, "status", "--porcelain") == ""
    assert not _overlay_path(skill_repo, data_dir).exists()


def test_refresh_replaces_only_the_generated_file_and_never_the_overlay(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0

    generated_path = _generated_path(skill_repo, data_dir)
    first_bytes = generated_path.read_bytes()
    overlay_path = _overlay_path(skill_repo, data_dir)
    overlay_path.write_text(VALID_OVERLAY, encoding="utf-8")
    overlay_bytes = overlay_path.read_bytes()
    other_generated = generated_path.with_name(f"{'b' * 64}.json")
    other_generated.write_bytes(b"{}\n")

    result = _refresh(skill_repo, data_dir)

    assert result.exit_code == 0, result.output
    assert _line(result.output, "refreshed generated skill: ").endswith(str(generated_path))
    assert generated_path.read_bytes() != first_bytes  # restamped generated_at
    assert RepositorySkill.model_validate_json(generated_path.read_bytes())
    assert overlay_path.read_bytes() == overlay_bytes
    assert other_generated.read_bytes() == b"{}\n"
    assert sorted(p.name for p in generated_path.parent.iterdir()) == sorted(
        [generated_path.name, other_generated.name]
    )


def test_refresh_preserves_the_stored_skill_when_the_researcher_fails(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0
    generated_path = _generated_path(skill_repo, data_dir)
    original = generated_path.read_bytes()

    def failing(request: AgentRequest) -> AgentResult:
        return AgentResult(
            role=AgentRole.RESEARCHER,
            success=False,
            failure_reason="upstream documentation was unreachable",
        )

    _install_runtime(monkeypatch, FakeAgentRuntime(researcher=failing))
    result = _refresh(skill_repo, data_dir)

    assert result.exit_code == 1, result.output
    assert "upstream documentation was unreachable" in result.output
    assert "Traceback" not in result.output
    assert generated_path.read_bytes() == original


def test_refresh_refuses_unverified_guidance_and_preserves_the_stored_skill(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"
    _install_runtime(monkeypatch, FakeAgentRuntime())
    assert _refresh(skill_repo, data_dir).exit_code == 0
    generated_path = _generated_path(skill_repo, data_dir)
    original = generated_path.read_bytes()

    def inventing(request: AgentRequest) -> AgentResult:
        profile = request.repository_profile
        assert profile is not None
        guidance = SkillGuidance(
            summary="Invented guidance.",
            guidance=("Use the newest release.",),
        )
        skill = RepositorySkill(
            dependency_fingerprint=profile.dependency_fingerprint,
            targets=(
                SkillTarget(
                    ecosystem="npm",
                    name="react",
                    declared_version="^19.1.0",
                    resolved_version="19.1.0",
                    evidence=("package.json",),
                ),
            ),
            official_sources=(
                SkillSource(
                    title="React documentation",
                    url="https://react.dev/reference/react",
                    version_scope="19.1.0",
                    applies_to=("react",),
                ),
            ),
            simplify=guidance,
            polish=guidance,
        )
        return AgentResult(role=AgentRole.RESEARCHER, success=True, repository_skill=skill)

    _install_runtime(monkeypatch, FakeAgentRuntime(researcher=inventing))
    result = _refresh(skill_repo, data_dir)

    assert result.exit_code == 1, result.output
    assert "refusing to store unverified repository guidance" in result.output
    assert "react" in result.output
    assert generated_path.read_bytes() == original


def test_refresh_refuses_guidance_for_a_different_fingerprint(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "data"

    def mismatched(request: AgentRequest) -> AgentResult:
        result = FakeAgentRuntime().run(request)
        skill = result.repository_skill
        assert skill is not None
        return AgentResult(
            role=AgentRole.RESEARCHER,
            success=True,
            repository_skill=skill.model_copy(update={"dependency_fingerprint": "c" * 64}),
        )

    _install_runtime(monkeypatch, FakeAgentRuntime(researcher=mismatched))
    result = _refresh(skill_repo, data_dir)

    assert result.exit_code == 1, result.output
    assert "different dependency fingerprint" in result.output
    assert not (data_dir / "repository-skills").exists()


def test_refresh_refuses_when_polish_is_disabled(
    skill_repo: Path, tmp_path: Path, missing_data_dir: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    config_path = _config_file(tmp_path / "factory.yaml", missing_data_dir, polish_enabled=False)

    def never(request: AgentRequest) -> AgentResult:  # pragma: no cover - must not run
        raise AssertionError("the researcher must not run when polish is disabled")

    _install_runtime(monkeypatch, FakeAgentRuntime(researcher=never))
    result = runner.invoke(
        cli.app, ["skill", "refresh", "--repo", str(skill_repo), "--config", str(config_path)]
    )

    assert result.exit_code == 2
    assert "polish.enabled" in result.output
    assert not missing_data_dir.exists()


def test_refresh_with_the_copilot_runtime_requires_copilot(
    skill_repo: Path, missing_data_dir: Path, path_without
) -> None:
    path_without("git")

    result = _refresh(skill_repo, missing_data_dir, "--runtime", "copilot")

    assert result.exit_code == 2
    assert "missing required executable(s) on PATH: copilot" in result.output
    assert not missing_data_dir.exists()


def test_refresh_with_the_fake_runtime_requires_only_git(
    skill_repo: Path, tmp_path: Path, path_without, monkeypatch: pytest.MonkeyPatch
) -> None:
    path_without("git")
    _install_runtime(monkeypatch, FakeAgentRuntime())

    result = _refresh(skill_repo, tmp_path / "data")

    assert "missing required executable" not in result.output


def test_generation_request_carries_only_the_profile_and_configured_sources(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Repository-level guidance is generated from the profile alone: no work
    item context, no changed files, no diff, and never from inside the
    repository or the operator's working directory."""
    data_dir = tmp_path / "data"
    captured: list[AgentRequest] = []

    def capture(request: AgentRequest) -> AgentResult:
        captured.append(request)
        return FakeAgentRuntime().run(request)

    _install_runtime(monkeypatch, FakeAgentRuntime(researcher=capture))
    result = _refresh(skill_repo, data_dir)

    assert result.exit_code == 0, result.output
    assert len(captured) == 1
    request = captured[0]
    assert request.role is AgentRole.RESEARCHER
    assert request.purpose is AgentPurpose.GENERATE_REPOSITORY_SKILL
    assert request.model == "gpt-5.6-sol"
    assert request.changed_files == []
    assert request.diff is None
    assert request.specification is None
    assert request.execution_plan is None
    assert request.change_set is None
    assert request.test_report is None
    assert request.verification_report is None
    assert request.repair_context is None
    assert request.attempt_number is None
    assert request.repository_profile is not None
    assert (
        request.repository_profile.dependency_fingerprint
        == profile_repository(skill_repo).dependency_fingerprint
    )
    assert "https://docs.pytest.org" in request.official_documentation_origins
    assert request.practice_reference_urls

    workspace = Path(request.workspace_path or "")
    assert workspace.is_dir()
    assert workspace.is_relative_to(data_dir / "skill-generation")
    assert not workspace.is_relative_to(skill_repo)


def test_refresh_honours_an_explicit_config_file(
    skill_repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    data_dir = tmp_path / "configured-data"
    config_path = _config_file(tmp_path / "factory.yaml", data_dir)
    _install_runtime(monkeypatch, FakeAgentRuntime())

    result = runner.invoke(
        cli.app, ["skill", "refresh", "--repo", str(skill_repo), "--config", str(config_path)]
    )

    assert result.exit_code == 0, result.output
    assert (data_dir / "repository-skills").is_dir()
